# Config file for automatic testing at travis-ci.org
dist: bionicj
language: java
jdk:
  - openjdk8
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37, codecov, style

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - java -version
  - javac -version
  - uname -a
  - lsb_release -a

install:
  - pip install codecov
  - pip install tox 

script:
  - tox -e $TOXENV

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
webhooks:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always

