# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37, codecov, style

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - java -version
  - source .travis/jdk_switcher.sh
  - jdk_switcher use openjdk8
  - source .travis/custom_path.sh
  - export PATH=$(get_filtered_path /usr/local/lib/jvm/openjdk11/bin)
  - java -version
  - uname -a
  - lsb_release -a

install:
  - pip install codecov
  - pip install tox 

script:
  - tox -e $TOXENV

after_success:
  - codecov

notifications:
  email:
    on_success: never
    on_failure: always
webhooks:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always

